version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}

  sentiment_service:
    build: ./sentiment_service
    ports:
      - "5000:5000"
